apiVersion: v1
kind: Service
metadata:
  name: vote-ui
  labels:
    app: vote-ui
  {{- if eq .Values.voteUi.service.type "LoadBalancer" }}
  annotations:
    {{- toYaml .Values.voteUi.service.annotations.loadBalancer | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.voteUi.service.type }}
  ports:
    - port: {{ .Values.voteUi.service.port }}
      targetPort: {{ .Values.voteUi.service.targetPort }}
      {{- if eq .Values.voteUi.service.type "NodePort" }}
      nodePort: {{ .Values.voteUi.service.nodePort }}
      {{- end }}
  selector:
    app: vote-ui
